### PR TITLE
Merge pull request #2 from MerlijnWajer/master

### PR DESCRIPTION
**Pull request by maci0**
merge from origin

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
? :-) If you need any help, let me know.

**Comment by maci0** [comment]
Sorry, tried to merge the wrong way around :D 
Did a fresh fork now.

**Comment by MerlijnWajer** [comment]
Ack! ;)

**Comment by maci0** [comment]
BTW, great tool.
I was able to use a small mini computer. Add the Xbox 360 wireless dongle to it.
Connect 4 controllers. And clone the devices to other computers through an ssh tunnel :D 
Thats cheaper and cooler than getting 4 wireless dongles :)

**Comment by MerlijnWajer** [comment]
Glad that you like it! If you're willing to document the use case a bit more then I can add it to the wiki. :)

**Pull request closed without merging**
